-- MySQL Script generated by MySQL Workbench
-- Fri Dec 8 19:52:17 2023
-- Model: New Model Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema gameshub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gameshub` DEFAULT CHARACTER SET utf8 ;
USE `gameshub` ;


-- -----------------------------------------------------
-- Table `gameshub`.`buyer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameshub`.`buyer` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `phone` VARCHAR(15) NULL,
  `email` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NULL,
  `password` VARCHAR(72) NOT NULL,
  `balance` FLOAT NOT NULL,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  PRIMARY KEY (`ID`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gameshub`.`seller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameshub`.`seller` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `phone` VARCHAR(15) NULL,
  `email` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NULL,
  `password` VARCHAR(72) NOT NULL,
  `balance` FLOAT NOT NULL,
  `NationalID` VARCHAR(20) NOT NULL,
  `Vat_Registration_Number` VARCHAR(255) NOT NULL,
  `Date_Joined` DATE NULL,
  `SellerDescription` MEDIUMTEXT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gameshub`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameshub`.`admin` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `phone` VARCHAR(15) NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(72) NOT NULL,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  PRIMARY KEY (`ID`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gameshub`.`PhysicalProduct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameshub`.`PhysicalProduct` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255),
  `price` FLOAT,
  `description` TEXT,
  `sellerID` INT NOT NULL,
  `count` INT,
  `postDate` DATE NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `SellerID2_idx` (`SellerID` ASC) VISIBLE,
  CONSTRAINT `SellerID2`
    FOREIGN KEY (`SellerID`)
    REFERENCES `gameshub`.`seller` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gameshub`.`DigitalProduct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameshub`.`DigitalProduct` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255),
  `price` FLOAT,
  `description` TEXT,
  `sellerID` INT NOT NULL,
  `count` INT,
  `postDate` DATE NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `SellerID2_idx` (`SellerID` ASC) VISIBLE,
  CONSTRAINT `SellerID3`
    FOREIGN KEY (`SellerID`)
    REFERENCES `gameshub`.`seller` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gameshub`.`Physical_Cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameshub`.`Physical_Cart` (
  `buyerID` INT NOT NULL,
  `productID` INT NOT NULL,
  `Count` INT NOT NULL,
  PRIMARY KEY (`buyerID`, `productID`),
  INDEX `PhysicalID1_idx` (`productID` ASC) VISIBLE,
  CONSTRAINT `PhysicalID1`
    FOREIGN KEY (`productID`)
    REFERENCES `gameshub`.`PhysicalProduct` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `buyerID2`
    FOREIGN KEY (`buyerID`)
    REFERENCES `gameshub`.`buyer` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gameshub`.`Digital_Cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameshub`.`Digital_Cart` (
  `buyerID` INT NOT NULL,
  `productID` INT NOT NULL,
  `Count` INT NOT NULL,
  PRIMARY KEY (`buyerID`, `productID`),
  INDEX `DigitalID1_idx` (`productID` ASC) VISIBLE,
  CONSTRAINT `DigitalID1`
    FOREIGN KEY (`productID`)
    REFERENCES `gameshub`.`DigitalProduct` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `buyerID3`
    FOREIGN KEY (`buyerID`)
    REFERENCES `gameshub`.`buyer` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gameshub`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameshub`.`Order` (
  `orderID` INT NOT NULL AUTO_INCREMENT,
  `buyerID` INT NOT NULL,
  `orderDate` DATE,
  `order_price` FLOAT NOT NULL,
  `order_status` VARCHAR(45),
  PRIMARY KEY (`orderID`),
  CONSTRAINT `orderBuyerID`
    FOREIGN KEY (`buyerID`)
    REFERENCES `gameshub`.`buyer` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gameshub`.`PhysicalOrderItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameshub`.`PhysicalOrderItem` (
  `orderID` INT NOT NULL,
  `productID` INT NOT NULL,
  `Count` INT NOT NULL,
  `unit_price` FLOAT NOT NULL,
  `total_price` FLOAT NOT NULL,
  PRIMARY KEY (`orderID`, `productID`),
  CONSTRAINT `physicalOrderID`
    FOREIGN KEY (`orderID`)
    REFERENCES `gameshub`.`Order` (`orderID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `physicalProductID`
    FOREIGN KEY (`productID`)
    REFERENCES `gameshub`.`PhysicalProduct` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gameshub`.`DigitalOrderItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gameshub`.`DigitalOrderItem` (
  `orderID` INT NOT NULL,
  `productID` INT NOT NULL,
  `Count` INT NOT NULL,
  `unit_price` FLOAT NOT NULL,
  `total_price` FLOAT NOT NULL,
  PRIMARY KEY (`orderID`, `productID`),
  CONSTRAINT `digitalOrderID`
    FOREIGN KEY (`orderID`)
    REFERENCES `gameshub`.`Order` (`orderID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `digitalProductID`
    FOREIGN KEY (`productID`)
    REFERENCES `gameshub`.`DigitalProduct` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- End of Tables
-- -----------------------------------------------------