name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: gameshub
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=10s
          --health-retries=10

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v1
      with:
        java-version: '21'

    - name: Build with Maven
      run: mvn -B package
      working-directory: ./Backend

    - name: Wait for MySQL to become available
      run: sleep 1m

    - name: Run SQL Script
      run: |
        mysql -h 127.0.0.1 -P 3306 -uroot -proot gameshub < Database\Gameshub_Schema.sql

    - name: Run tests
      run: mvn test
      working-directory: ./Backend
